apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:kMeWUvIwWKGXLtjjjT3ChVWyBSOzX89tzAu0iaH3mVJnD28iAuW+k96zy5XHjhkl5Ey3SoEmwMfhGeCwBZ7/7W0=,iv:1XglGHE308kG+o61b+O2uOzVok+zyZ4LequHwbC6enY=,tag:+u3eeDaXrHPmXbsI1SHfQA==,type:comment]
    #ENC[AES256_GCM,data:208aSxY9ct8rN2FWSCNszVfB7WsqW48otBDtF4B4y6JswXRACmkvPvlXQos=,iv:M+B5y/Yu5YyPuFqSNrIyvB1KHaa1c3pY1EgA1gfOlt0=,tag:Dp6jOp1qxE1aV1HNC7puIg==,type:comment]
    VIP: ENC[AES256_GCM,data:Q9vJyDldYhayD1E0hQ==,iv:JXdvyabTruZFs16vJGH4mqSflbBpphTecBlDsERR1CA=,tag:5826zeusd6OgEIA9tamfVA==,type:str]
    #ENC[AES256_GCM,data:GMH/0INqm3+D7CZShVJVuW1wOZBbk9vXXvY=,iv:XfXNG2xZi9nOOtP0gaBP6VhJ4vB7tOjgo7i84O9iB8s=,tag:NOPKbCnzmHYruHSg8arNrQ==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:Asp1JEW0BWwwMNZV9hk=,iv:i63aEFKartJ4CoMzK4xEJyjD7o2510k17Br5+W7JROE=,tag:1u48ySXiTPxHNaNMYm9w7A==,type:str]
    #ENC[AES256_GCM,data:8BG+fLHam8dUu2J/YOHuO/VWKzB1ukxRpeQZKLaJehPrsQ==,iv:EAs0JOf2WFE+AzcsKObEAqGWBc2hEHxwkYgUMaJFx8g=,tag:EEFThPvUvyargYSJZlFaWw==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:anzBEnOofobeN4LG,iv:GHE+Uvl3+VPizsbfKfU6e/j/rgP0OpywA1/eChsEZQ8=,tag:dsZkvFbDfxEMDf0AdrDrYA==,type:str]
    #ENC[AES256_GCM,data:lEUslqnX380KQYnNEQk8V3PKRah2X52Mqtmzo5CSIuyuQCgOB4mNNn2HQFiLrXc=,iv:2XfGiQDvJJc++6+f9R2NIn29XtdOvEjVbHFnHgCMFEs=,tag:p9BLQ1nW47Cmzm5rkJ6txA==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:9Pjyvv1lCpm2XyEuzDH0hRxcKQJKtqDz8BXR,iv:r/yLj3d5H5RFCMag1KpYYUpzfqD2YcFDGz5Y60CXY64=,tag:bPNGQ7hhWo9LWTShNt5lJA==,type:str]
    #ENC[AES256_GCM,data:etJUQQIUADdPJpy3rl58djPYA8VH7Oa+GnXPKlzQBqlT6Ji+Nw69Usk8bsfedkLiB+9zedTU2FD/NJ84jiG3Y4C/BucLYPbYhPRul/y3w8c=,iv:5NKrGwtX3QXVjbZvaieWuz6hgYTiNY8f57Hxy+7li8Q=,tag:SWmPnNa8uZtP2dJLe4v3sA==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:2xzcwyM1yiXoCfbZXQ==,iv:b1Z/KmdqYfCfaxshENx3vNEZRQNlzCY8f3I5kylrP7I=,tag:2gSPwHWdxh8bMHACta2Kqw==,type:str]
    #ENC[AES256_GCM,data:r3c7mzKxOwHtu13uqfyiG0BBih6qL6694mSCm6Q782q4/tCLv+l9kWVaaIYsiPsRWO8urCFpnYA=,iv:F+Ljsrsb4x008CYpNrfV2vEs12NZQX59VREDX0DEiM4=,tag:E0kA0UtQNgbCgpWIGicE8w==,type:comment]
    #ENC[AES256_GCM,data:1NXUkaIVIdcB9av6rgOhOAMnsLsf4Xwtpg==,iv:wq3Mt9arAK/7nfoKHDSbDhokYGhGUpHmFSpQPodurww=,tag:zHIiT+igeQtkCrc20iT6Ww==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:fjwwMLQei1bjQbYi8JvitL7DbxLLC/Mx8i8+zergD/MOAM2c7eRHMn1YGg==,iv:DJ2YHUJzM2m5wd79LvvKZ7SWHwWXOrh33noE0l3lyuA=,tag:Uji4zTt98vl8p+Wq7/cgeg==,type:str]
    #ENC[AES256_GCM,data:zzWUjgu1ov7v6f41Bg==,iv:4TipRm47TJ+uA497lrIj1cTjgcIpQrgFD94DfqbDp5Q=,tag:/4Xmzfllmx6paPCIfUOldA==,type:comment]
    PODNET: ENC[AES256_GCM,data:B7ubbkCwsquipSI12Q==,iv:407V8k2utewYoi4Sy9SrJjHNNv0Vvr5S2bXfg0nuNHo=,tag:ca00Gg+zBFV7E/50EH63FQ==,type:str]
    SVCNET: ENC[AES256_GCM,data:nwOTdzGwdRKKLUyyoQ==,iv:l4mJNaNrglccsOmSxoAHRsYPs9sWR/cWAUh1ds7ylh0=,tag:xGd9lD3l3rcdK6BvJJGjwg==,type:str]
    #ENC[AES256_GCM,data:EKMDgt0+g7NdmQ==,iv:bRBB+I5VV+N6s7F/HNRbRQgJCHFA0gsTqpfEf0IwfOs=,tag:h1FQS/akTipyEojF7s49IA==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:IAxQJNpnVMZgS3xLSg==,iv:2gppFG/Bk1DB/J/f+8slOPD04iCgQePRwBHjmP+398o=,tag:EchsVPj/0wAS0bSM4spBiQ==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:FU7KaKaxVQAPGJgPPw==,iv:0L9d6AsG2jjxHAZ28y+xYVsCHJgzHABd5C7MgVQHars=,tag:mI/0mc8posKfAFJe8WZWCg==,type:str]
    OPENSPEEDTEST_IP: ENC[AES256_GCM,data:eqVE7DykGkzAYOTTdQ==,iv:z4bYJuCtIyt/lRniP/Q6DxM9e+ZuWWYLgGiAVpYmurI=,tag:m1qGx9ESdipohIU3r+ICtQ==,type:str]
    MAIL_IP: ENC[AES256_GCM,data:ec84e0e1ww++MN75GeE=,iv:QvCXYV0tyEa68Vb94v1XJPlMSfwxZnP13YzL+QX0bsc=,tag:8L+RdxOmmSFjLrvR5b7Ybg==,type:str]
    TRUENAS_IP: ENC[AES256_GCM,data:HW3hUE3Y2UzqFRFuaBM=,iv:H00mJamrzA0uMOL5biDC5hyg+43XUjQoODpXmBqCAq0=,tag:vMIJzF89uoTIYuJtuxuxgA==,type:str]
    HA_IP: ENC[AES256_GCM,data:aCNY0mtaCBYnhkmHqnQ=,iv:KmaGA6l9dlCCqeOkcqQ0sLP8Kze11JohzlZUIm8YcT8=,tag:hNtIrPPPYI7goLAD4ww/eQ==,type:str]
    MC_IP: ENC[AES256_GCM,data:VtfXPEZ318kFL1b+tzY=,iv:M+z/5eKPw/9aaxM9Rs8vyKS/a/y2EVhO9sgxLUGgUM8=,tag:US4R6b+hLLktWm53cZ92ow==,type:str]
    WIREGUARD_IP: ENC[AES256_GCM,data:scwVG5VvK/tIjdhJqhs=,iv:ZLg4N6ivseirSyOTw//E79SZlLFxTbCBE3z0vyD7iL4=,tag:d/LoIek5eAk6s5DsynIAKA==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:yKN4FrleldrHme11SDmmfmjj0qJ1NDM2Wlc6N8kxnPIGxBwqBSd35A==,iv:Kcw5fvYlJygST8oGPd00/93cr1/wtz0amuVSiwKGEEU=,tag:nDkanerNFCeCkx7znDHCBw==,type:str]
    EMAIL: ENC[AES256_GCM,data:lQkc0QyOqGmHoKVmS/ezRe7KCYVd+k0pJFdfeOkmKg==,iv:fknAm4WCZ+StiP+f0TOGsotGdI14/A0x07K3uivAGX8=,tag:qXfe4e7LJnsjoWaJfzFKlg==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:riBGkjBm1JZmUSYr4g==,iv:LMwxuDXDASRlxHb6gzVP/GVGMmCLr2r1/kjsOfwHw6g=,tag:asZv9PFbQAoT8rU9i7Jc3A==,type:str]
    MAIL_BASE_DOMAIN_RL: ENC[AES256_GCM,data:t+oEF0mMPbOJTLgGDWsuM66fUaajP2E=,iv:jzeFy73R8OFP/yBvTg3zIRMkzp2zKymR9JiZoAF/lLI=,tag:6n/cENwAZP3RbWqeg5yRKQ==,type:str]
    MAIL_BASE_DOMAIN_GCL: ENC[AES256_GCM,data:k/6V/2gYJE6h22SEKRDyQZy5GrC10kgnFjM=,iv:5REMBYcFIngcfkXq6YjF4oHXT+UtjC0pVyN7BToFWo0=,tag:NglVnmzYg/rx3bPstZxeKA==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:Nynj+Q==,iv:VncWbf3vhgdmw/xdZ1V3xpYlhLpIMzgJyyL3vE0rVXI=,tag:QFytvXCIuoX2gG1XsKmr6A==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c8f2w7vn06fj2chqaq274g66mg9z9sf9s4l33wmf7m99g5w2nafqlunj9f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxS2NCRCtobWd3MlVPR0E1
            SEszMENMdEt2QXZNRnhuRzR5bVdhaFJUSFRBCmIxcms2T2NidnBLa2s4MnpmV1ky
            MDEvWC9YTi8wMjM3RS9NdjFUVE9RL2sKLS0tIFpWSWt3ekhSbnhqSzZydmhPcUxv
            THVIYVVkenAvd0YxWnF1WVQ2R0tDcUkKhk6R6BPWw/MREXnDxjjFRwaHqAXX6jwY
            ihPAJHp/2sbSvXnfHnUj7nxmLNoZceJoLIduomb7qRsmrrQY6iLZIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-17T15:42:40Z"
    mac: ENC[AES256_GCM,data:cgihewkC+awLB39oNXmdpMWQmPRuQVgBGusQe/jEFFDoYqatxrGAiYQUBxtNmqDANSIRlkj43tC6ctVM5MSII3wWOpfV+F3ts/+C4cJt0+E7bUZNtHgE/pMyUSnGGaER6IGQEjCxBF9CDt0ue8hNJNs2cugKRC7FSxEfwKsLnBk=,iv:wB8Ouwsj/zK7nVmrC624eWcPzV2XB4AfseNGeCTKnVI=,tag:9V/nuXLgUc8kT4jiLkYVDA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
