apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:9CjqeWOzwjms3fMlY6Ek9R9F9qzYkKtURR34nOUPSDixD491otBtYB2JEr9RlOBlIx0ck9F1xNfnp0PSTzKbSCw=,iv:2pAOeEJPj2OPczJ6GS0WvYuMqumHagZ8GL4fEmN8iZ0=,tag:M2rrzCTh0Z8P9p/4r8ugHg==,type:comment]
    #ENC[AES256_GCM,data:lNpT5SYzeZq+uPUZEp+BnTUnM362jXqlxop/pEF8ulRG5CjMhqriIDW6mtk=,iv:VwVUuU4RI7eHotYayKbFK3/yK8OvXUtLxQo6/i8IJg4=,tag:J38t75/NI5PTK/tkJWUptg==,type:comment]
    VIP: ENC[AES256_GCM,data:Z9pD2JhfS17UhRdmFg==,iv:1YhKQvBxrn28ox5P6I26bdkxYqRuh3gYQm5r8fwEKns=,tag:B9oUvnc2zx97+UZ4aFsKkg==,type:str]
    #ENC[AES256_GCM,data:CYRXgp+mXuT1x6bLIhnDw8NGVFCfU/cJ1Uk=,iv:eVyokiH1HrIjex/OzixFrTQ+OPqYK6KDPcS2MupAGV8=,tag:56FSPfnR/EU3QWi4hRuwag==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:+mUXrlKmc228+qpFCOw=,iv:WknNGq2WpLgYTcG1iEjLWGtJ4mh428eRCYILfZu9aco=,tag:EZTAVvaWQ/j9jasJnT/0QQ==,type:str]
    #ENC[AES256_GCM,data:oK7ESWoFjhOpcD0VDnYKskuKUzub4jKr3Kws1Oh+DPvzsg==,iv:iXF51hzyfsNBrTDAs1a2yTLqqvLOvCtlT/H0KZGtRNY=,tag:r2mI9QVkksdlCrBzJLHpng==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:08PKsYNdRc3pnZv2,iv:7Z15PX/BnKJPkSRD+mD93LvsyWdpbFKKr6gDnBBB1+M=,tag:3rUtuPpyne0hZaRwpi8VtA==,type:str]
    #ENC[AES256_GCM,data:wGj45AUUwRE3AcUnOq/prwCQ/MA9/QN9iVjJtJB6mcWXNXQoUUzoXEyLKJ+1Wg4=,iv:qS1H8g3MPT37d6Y/mqIkKdCMx+feJukX4ZI3VY+GwNM=,tag:xRu68sG/XknSf2CxY9/SCw==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:VjG4m5a9VZRElGwmn1TMN8nFfCI8a1PSCc6f,iv:zMg2NFGddMdRiaPbqIEZAhOSQex/vALitPyJeIKrI74=,tag:Fywk1U99liVvcYE82r3pEA==,type:str]
    #ENC[AES256_GCM,data:ovSvlb2gB8cUfG70mOPVyWsEiVonDz9SLfwnGz71EAAMlz64HTRdI9BRJjWdD+mbl9Nno7V6LbDK9UQz1NzsKboq9nyWCZHXnWq3u6yOdOQ=,iv:LZutoGi+U79uEXTh45yafzZ80UBJCRLYKJFdDkbbI+w=,tag:s75okaok+Z+a1adUWbfNDw==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:jFgPFx7ox6X3b2aXCw==,iv:bOfrE+3c+VM1PJYtYAAzBPxQvT4EBA5TpoZCynp57AI=,tag:aqFnxfyoNpeeriw7HjrpYQ==,type:str]
    #ENC[AES256_GCM,data:JVOrb3ENzsI9+3wtHLWvI5bGfjwVDQXx1wtk5yGpm+/pH2QuQLIkTr3L+KrQemPIxUDpeH9SHFE=,iv:Thn1xuwA3gUPyKsKZbuoung6fSw/bhoU7p3V1QfeTfw=,tag:naJ7agoTLw23NiQCzOCE2Q==,type:comment]
    #ENC[AES256_GCM,data:KGwmiZOMNs6tVgeLig7X7TXF9jeMgdgzZQ==,iv:QRxdDwtV3xU3X56Bv2EJJ9FZz/VJcfWuSqFGze2bd9c=,tag:ozkYVrMX6b4LeRuhGpm1VQ==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:ldzBGXk0v+fP0lpon0raUPbXGaQhOpwHkFjiTo0yOpS36wbaBk+3S3iEtg==,iv:TjnNVMQUO0GyVgdrWr83AKX0FFshHcHQpowUzZhySRQ=,tag:Oe6d5TnZYD6D0iG4i1TEag==,type:str]
    #ENC[AES256_GCM,data:Dk8pcDknZHJntxAZ4A==,iv:a7Xb2HNy8Xx0IH2gtQiD8pz4psgaFXWVQdfByG6JeKg=,tag:1uh1BuSTSpXRTwxdmywoIg==,type:comment]
    PODNET: ENC[AES256_GCM,data:r24G1nE2PBkCflsytw==,iv:POaLG3SCWqV+kMdrRex0Gp5NL1NQRY+eBLF0Jnw0gIE=,tag:SGucGnRJf0UquPvLj7sHQQ==,type:str]
    SVCNET: ENC[AES256_GCM,data:Gc8ZAETJzx5Zov89lw==,iv:IzSYC+oXFg+3voBSnHYWu2zWDZeTeSt3s2v+wlVyqDc=,tag:FHmPIAcnlfp5QG2xA6+dNw==,type:str]
    #ENC[AES256_GCM,data:BziJQSCdp/DSsw==,iv:K/uAgbl8cS7STEG2sauo1GnFhNTt1gqtPcG78N/7lxw=,tag:vujKSdEamoHF+AUu2LL5QA==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:wysHtBq88MT105SF0g==,iv:b5a3DAjs+usv+OKtnIDYyD6I0WK08xBYfideRb1mhUA=,tag:jLAVd0tRCcqeXAX/vI46Lw==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:C9lTRUdYNtYeiELR9w==,iv:Wy0zTu8+XzaRnyxuqysesp6bpiEVPPXD1VIw60wgFr8=,tag:sfUqDVvxL3zChpMITEnnIw==,type:str]
    OPENSPEEDTEST_IP: ENC[AES256_GCM,data:iFqks9bXg2yho48Z3w==,iv:9FdDoKkQlMxnoHw07+WkysZ8ASrnT+AQzFMLI6KPOIU=,tag:re7CtWIKYwzG0ZyFkX3TmQ==,type:str]
    MAIL_IP: ENC[AES256_GCM,data:4wFcXLFecUvm0Bd5Qdg=,iv:GixSf6Q0EBghRVbnNIOPCbIoZH4M0VyGx41uJipnxxo=,tag:iRx8Wwn+y8/BSGzAwQQiYA==,type:str]
    TRUENAS_IP: ENC[AES256_GCM,data:tdeCMIp9HQLtDKr1FAM=,iv:we0p94E0Vep7xZ3HIIW19XfAS9HUlq/ZCPScRj3STVA=,tag:A+dNvLXFMrrfmg47uDXrYw==,type:str]
    HA_IP: ENC[AES256_GCM,data:Sp1Z3vH5drVVmKMxTHg=,iv:YjdhiGd32FWJxWxrNJ2msdWkQH/cmIsKm+y6gzMiUnw=,tag:tH6cDFYdezR6pwne0pOUNw==,type:str]
    MC_IP: ENC[AES256_GCM,data:NdPgbS4H3XxJSy8LCd8=,iv:NvJVdXztyHQzh9kKKJszgqgiOLFjp9cAFTuzYarqAJs=,tag:12EkKu9Bnolfr0cFI3vKNw==,type:str]
    WIREGUARD_IP: ENC[AES256_GCM,data:JVRWcsm8C21xUsPqzW8=,iv:5vukAnnLipHAOvPz2PJv5yX0oQpf7eZJUi9H0x6rtUw=,tag:y7x7TuML771ero3nxksetQ==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:3JhNIKXJy3CcqVyi3HERyPyi5zFHwo0S55GC+A5oQ2e6lMlC8YjXBQ==,iv:aITH6MJi7BTtMUOFnz0aMa8Tn6M2Tb/dQ/znGy7ms7M=,tag:FB7tYhu501JlB1i74HwXJA==,type:str]
    EMAIL: ENC[AES256_GCM,data:wK0lNaeMzLQ5+Mp/HXhQ8n14N+Iy9guPlZ6Ma48gsg==,iv:ghTRP6Y+e58Xf6vUUnTtG1mTAbMUo8sw5n7ENiBOe+4=,tag:eWQiiaON87tCWQ95VDlP+A==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:sjRVwgCnZZTc0qw+sg==,iv:3ZHMvB5NYGpO/yfMs96KqvQSvSBsVmniCi9AAXY09bE=,tag:xCm8cr8pfokcrgryOMXKBw==,type:str]
    MAIL_BASE_DOMAIN_RL: ENC[AES256_GCM,data:qqyBxACOFPJSmgMfePegJgv3ZpQ6ZcQ=,iv:oupEPKF3rgLa86lpHfxMf2pu8zC1XuOCOW6+BtAiisI=,tag:SOMZlu2OfdpA8vDj8o+0Yw==,type:str]
    MAIL_BASE_DOMAIN_GCL: ENC[AES256_GCM,data:YvuhMGu/bnwN/4ePzgA640NtmRIDTQ45TFo=,iv:8fSptA1tarpYCb/eVwgsMqZchazya9atg5kROi3vzpM=,tag:AX8zhEFqb0FN6va8/4+VWQ==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:dsGwzg==,iv:8aXjj0g8JMleaCuPNHxxuunct+d6VrIAMZHxV/DzEUQ=,tag:i2pkJYwHlF+8JqILNVMKYA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c8f2w7vn06fj2chqaq274g66mg9z9sf9s4l33wmf7m99g5w2nafqlunj9f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaTTNpRklwMS8wWDg5Umw2
            ZWpIRGV5QTlVTVVITHFkQmYvMEhMUTN6MVM0CnhOdnF2TXNVb0tlekRhdE1VUXNp
            K21pM2pXNCtOKzEwV0l6Rlh3b1dXU00KLS0tIGdGbjJsVGRmeXVxQld2RzJNZ01N
            REFYNzNCSWlwdFI4Q3lQSExWOGhPbjAKyST1XISOg/fW6ccFI2JQr1TCZQKcKkmQ
            ytWZ4PB++d8QEjlY7wzJJYaH4I8F9ri8kKuPssq5A1wOWdXF2rLPrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-17T00:52:40Z"
    mac: ENC[AES256_GCM,data:UnsJ8QMJv8xKfPuIZ2MqoJXBfB/Xjppkv7PZh3a2GyRGFg/Bbazm8wHHGnxnbzx+WwVGEGex/wCJtwdm3nmaAy2akABGphTW0t+lkohlpgW7uxDFkAqkwliIGJLZvGjX/ZBdnpPQ+gYnl0+fpu+HjdjNzBo45ld39RzTetR6Gio=,iv:6eNrNrb3awPoyp8pi0mZaxjnCPuWDBFoP71WD9krAVU=,tag:HhS1efLa0pRqEVaoBgdFXg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
