apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:wNZ7qjB9bZXREHgrx9+DXk8L8clKBtBivhjlJqFi10ylWc83JvenHIalHgAMkPXwYqGJo7eKFrKHC/j+Adbb33g=,iv:UQUzhS2S1rWtCTwJJke04+nHJpCSz+c+c8VEc/5fmKM=,tag:oIvwKAEZ1736r+iOXxzMug==,type:comment]
    #ENC[AES256_GCM,data:ctwZ0X1LlmIDL2EgrXBFRxg11pnzJx/XA7zdm9RPtwLfMZ6+YVSUrF/pr/U=,iv:wylv6lSW257267WTKFTcKipbl4hXOhmbzQtnSzEzeWk=,tag:euDVMY/M9ssIRt0p/7Prug==,type:comment]
    VIP: ENC[AES256_GCM,data:XwW0PDbsGnKFcnQbEA==,iv:pDqu3IiSxxO94U0rSHLRr3vHfIbITx9HdmPSxPyhf0c=,tag:WUmiBLNrItsqFY4uUAPi8g==,type:str]
    #ENC[AES256_GCM,data:ILrjJ0GORHqizfTTEWcQEs37j9qx1i6pwRw=,iv:6ZZjpu7PPVrALt2y+vanLZUvbQIHmRdlWgMOQ9qnras=,tag:zDufeFZW+bb2jxPbKi8JAg==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:f5wMq385+9/jNI4qdXA=,iv:xGV+Rkxe7G0dw92orzt25HLfJMmsUqmoi4ypq4YlATY=,tag:GQ6q3AfZmWICqbJ5UdBIRA==,type:str]
    #ENC[AES256_GCM,data:rkG0AzGqLlUWr6fYr772YDgCc5nAWvycKitOmPdS/rs8ug==,iv:P2kv+TPabXsezwowCzX6loGw2p4WjzwSTOXtlFChouk=,tag:2rkm07zh0KfWGTY/SX/hkQ==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:3HtT8L5KbtMmqIIb,iv:Gbl/KdApHZoe7eyfZjuUJgAUDNYSLUK5d0RHOErtEQE=,tag:tPXd9OhOf2TXOwBkMjieVQ==,type:str]
    #ENC[AES256_GCM,data:JMtCGYW82hrHODkf+tdy99zzWXEre+EUrYMKUragomeFMQsCIeu7Y/Xs4qUI7wc=,iv:UjN8kVgMM/tjbOBDvb7HbjFLOnKpc7jOSE14k+INGLs=,tag:LjwGarP02NyWaKEGX3ZoKg==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:kv+TwKEu1Nvd06JjraQ+WGfrnKKJGx+KhyEO,iv:TsDm7htRUyxmxQX6+JOxvPnB9ObTZkAjSTtQAnphsRk=,tag:60SEyjmpZdh4JeREcXAhmQ==,type:str]
    #ENC[AES256_GCM,data:+ylzSbhTKWqQM6ApHiPpshnLZFBZvDGd+u6sXH4Y3kWCXYeMKt8QF+YxVyWXpUmHd3GfsVLJ8sAsMC3IUZyIGEXVySvydRvvjsWtcR5HiZo=,iv:69ARHjAmTED8tgvqfxv7C92/XNByAduPyhIAZJRP6tE=,tag:y0I5dOSSssesD71suOKdBg==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:JF3GQ4E6ndN+A8qihg==,iv:Ka0BufmC2BDyxlSQaWzGIuqIMzh19VA+xo1xCY1UU1o=,tag:YRSOOVw2AwSedM+hQ8VmLg==,type:str]
    #ENC[AES256_GCM,data:kBZtx5h618B43j0qJVeyCeg82BWAzotOSeVmPcDse6NiwR2KwvecEmLCW51MjRuGb8EVSXp0rUs=,iv:At/ZdWvdzKQGTGQ1NuzY2AKe83SQo8S/6Yg9YQ/4E1c=,tag:k7xGr/hKCa4QqS1B5vS5NQ==,type:comment]
    #ENC[AES256_GCM,data:FFT0Z6nQUC6t5zdGmNFPB+SEK35aShXoIw==,iv:d6UZ6GhzlMo8zBbLSuOkm6xYWV9CDSrq2A3P1tFvJaM=,tag:MKtrVFwUKwTpfmp4FDyygg==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:2FeZ3MJP+SGx3+d9BDHxVW9bn4ADweCH/CgpiUrpv8cauTyBl83QjAEhsw==,iv:PY/Pq8PVKw8r1Hs61jRCdQeau6Nkch4Vn8Mpg9HfnZc=,tag:g4+/ldzLJh+23UL1b7sblw==,type:str]
    #ENC[AES256_GCM,data:N3O1G+Ua5pH5p6PiXw==,iv:bV2nmMIrfBOpWzSolTF2lcNUOjlNZrfwyurz2j7D+lI=,tag:+/2vXVxUmCFb7zVPNDYeBw==,type:comment]
    PODNET: ENC[AES256_GCM,data:V67P5l9ssdZ8hQUEqQ==,iv:d0e6SpgUna/kjs8XYG7P/J/DSZyK7OiREpbgiAPDEn4=,tag:eSsI6ELRpazy2BbKvBWSlg==,type:str]
    SVCNET: ENC[AES256_GCM,data:zC2B38mXr7PP11rysw==,iv:8JZhU+5ECdRLbeH42W0/t7cEOERR1ZGba1YifFK1TPQ=,tag:sz4tu+6ShvbsfF7XcEwN5g==,type:str]
    #ENC[AES256_GCM,data:MfYrLx0Ni8XvqQ==,iv:8Ckxkrpn1wrvOZ/e6R3R3fkObfegGxTG22a4HLzVRdU=,tag:/QuPU1m9E2JLzwgEGFMRPw==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:0JEV34GfvrU2z+DhLA==,iv:8O3w0ov0MtD04/3R0VVPe6oQodvRJyJzo+2IMZ8YV5s=,tag:c2zRMg9ZQFMJksVL+5P1rQ==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:PwD6EWKk3URp2a7g1A==,iv:raSRgMYhlZQV2020d0KLwtZ6PZH9W2q96GtABeRehPg=,tag:o9FSntWP/A1AfnXqzdLx9g==,type:str]
    OPENSPEEDTEST_IP: ENC[AES256_GCM,data:V4kZdkeemvxrJHqr/g==,iv:mC9ZPNoIsnK6IxwNX8bmrKBXJIqwKLZ5VUjXfBC31Zc=,tag:reuS5vQw+jv3DfdfSDCE2A==,type:str]
    MAIL_IP: ENC[AES256_GCM,data:EJz977JLc0s5PUva5k4=,iv:1EMlCO6/ApfU7o4+VZq9MosTR0wI2S7CBwoG8YhSc6w=,tag:u6SiSBfUWmuy2X1h6ZO8sg==,type:str]
    TRUENAS_IP: ENC[AES256_GCM,data:V/onyYm/QIg/1E/uy/c=,iv:4K/uaISXC4zyRNGnKMPwJRABD52FzD0mUIXI3enKrEg=,tag:ZpQ3J7+UdFGQQoVW3N7Dwg==,type:str]
    PLEX_IP: ENC[AES256_GCM,data:OQiysLGT3BlIloJkNMA=,iv:YBBhJWTYTGVee4Wr2ZpggMwHesa+sRM+FQo6PQC4VeM=,tag:12vnDdIhc7HGi2ssUT8t4w==,type:str]
    HA_IP: ENC[AES256_GCM,data:jD+1wc8AZNkhMyfKfjc=,iv:sxAwGfOfkEYq4y2KXHozWsjx+9JdUWUnbqQb63rEYUc=,tag:tgcMXy/x7AFf/VqYrEu7cg==,type:str]
    MC_IP: ENC[AES256_GCM,data:W/O5o3VjHFziM6KcI80=,iv:pWrPjdncnrCPJUTimdJJh8y4IM1tr1jnPkzpINmPPZs=,tag:y/EfsdwiBpgIewnf0PN++g==,type:str]
    WIREGUARD_IP: ENC[AES256_GCM,data:fG0wxNFQJARdMD9kN48=,iv:tXzrhHxNCJhj9UeL5foaEU3aD7lzicFzWoWQ/v0avYo=,tag:52rO0HWNhmYcJ/csMTrOJA==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:1ShZzjR/e6AJYOWjME5BwmORRbyXY9imQAzDQeruYsW0kQpFO7y8Kw==,iv:E7WWBKj/T3Nanbf4F6CVsAgIlxrMvFDgYSpT/vgx4zI=,tag:NVcRfamhWMpPtVOD+eNzXA==,type:str]
    EMAIL: ENC[AES256_GCM,data:snDXxjC6MEoiecF3FUGTOjNmv4o2/nl25m3LjYiFPg==,iv:dB+qaR+sI5dGI4VIYcy9hJZjkdpa4wZ+Rr5fAY5PktM=,tag:qzg2fz2q/CGOili1s6OqSw==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:8waaQ3jYSlDwP8c3rg==,iv:n9+jbDHzQB61ykM0btETX6h72nmHrsXp2mKORScC/4o=,tag:qdrePQ7afhmSPIpx5cVnGQ==,type:str]
    MAIL_BASE_DOMAIN_RL: ENC[AES256_GCM,data:Uwv0yJ9GXjeTzDDC/nMNzRl24I/BwI8=,iv:6XUnRwkQI6rWvEGtr0kot977/E30AtnitOCsNfcAcnA=,tag:5NWg0EmIeSwAijzrJuYqeQ==,type:str]
    MAIL_BASE_DOMAIN_GCL: ENC[AES256_GCM,data:be5nLs9EwWan0zBoDBujbZ4FXB92DVfuScs=,iv:4Ol4j472D4srhXsiRIsyjnpbx67o01mxYTChzXTiHoA=,tag:dtSJ7d8P2/CThd3oHCfkjg==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:sB6Z3g==,iv:w18+dMwzts0GAaMfTtgfjkS3UG/e/jhfO/OCuFcuQ1E=,tag:uOxE1U/Uvewk/z7cWpsKSA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c8f2w7vn06fj2chqaq274g66mg9z9sf9s4l33wmf7m99g5w2nafqlunj9f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXS2kvQmZtOWozSXEyNElG
            TmVQNWJ0WHdVRDMyRmgyYnZEaTFBNVB4bnhNCk0xalNsbHo3VDdBNDEzbXhmYjBs
            Zk51a2d0ajN5Si82UWlCdElQb3RuS0UKLS0tIHhlc2NTd0RkS3VGalNpT1pmelBW
            Q1BhTWFTdUFUUDFITlF4U3JEK1NZeFkKxht7BZ+4hLexSeha3DKoNjkm7/9362H4
            oF7034UpR1effJaTG+nrG09BOtGuwjOTPfwhx5K7JNnQVsNIx9HXLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-17T15:59:04Z"
    mac: ENC[AES256_GCM,data:cpoBxFkgJh4DgvGGw8VCjXl/5D+mYm/Mt5y7dSYk3+BYJlYT0+wNF3kSLatz1fH5sQafcnZ+FlNnzdbrwUGxoNeqg71LxH4F1yCFJMe+LuC4X2mi73LgOtHVWkJYnhuh5OPQEL4Iw/rU39jLK9N95SX9/2o/kYo6vNXgcoFmKYE=,iv:s0noglE7tQ9rHZs/8P0GK9r2hf0fvoH9HnRGbyO8+UI=,tag:W4cCw0V84eZJPGDOiS+npA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
