apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:KLC9AGZtzUFm7ZrzuFLofVcgeQ/WCOrLwoVG9YYIv0WBYbNZpmeZDUati0jtLszuZqGW2pn3Craa9JtLq5m/+ok=,iv:sTljw37d7M40EIseZEsTLRQ2HUKOBQB97Mxt3nbm6NA=,tag:q06zDmCMUmbxqFidzhiKRw==,type:comment]
    #ENC[AES256_GCM,data:YFLVMbePPMtgZVO+XWsQeeI5bKzcyneHyxThtIPP1DcA8zqqtX47rI1JpP8=,iv:0GFzyssUlg9yrZcnwaidKhiC0rHoGXeL1NaTpqnPvvE=,tag:YhdUiG/J6dx3wtUMPwp+eQ==,type:comment]
    VIP: ENC[AES256_GCM,data:kkp/s3X92+Glb/Cbtw==,iv:Du3p4vBDA6MKzKPbpLD1jSTq0a4s73LRvxsTpDBIL14=,tag:T3fRC+jyuU5L86u7Yfzetg==,type:str]
    #ENC[AES256_GCM,data:gYOY4DkV0etpQuvFmkEMNsiMVWsVqBl6ddI=,iv:twdnubM8uAFjcps46dXFlHZFm9WmjA8Fh0//oQOUtqE=,tag:+yXeWegSjXfzyF5UjgUzsg==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:rn8hwsIWMFON3RSonXI=,iv:YkDtS2pm7gcO4Q9oJE8xI6utCGeBRnUn1zZpjyYdjt0=,tag:8EDCCf4zkly/NsGdq3OyJg==,type:str]
    #ENC[AES256_GCM,data:gLiBSG9m9HilInT1j08aa1t3bMnBPm2CJwrPoVvIhc5lAg==,iv:JgeXkEAYoNFyPq+eJPM/g0qlQBoGEUPx9TLDROKrRiU=,tag:/FM7lZ7FKzNQU4ezuXW2bw==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:+ucl8B0AeVP+oCP8,iv:RzGf/msEy5JHp19/Hj+dt0iGJudCBBX1LDvOL3uomfQ=,tag:wFIYaSwdS45LEapeKYZl7A==,type:str]
    #ENC[AES256_GCM,data:w94Fjvp8x0zd2tZdoYriqPmwNUX2b8fqDs9GgYTCx7B8yc3gvzx3z29DxkedoAU=,iv:V76iEgHUKaRosfkGihJ3IQY55XwSY0baflspz2Nr+v4=,tag:6E48OK+3EJp4nRBcHh9/DA==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:PF+KsRY8rX8Ad5Drg3YNdgBtXBakBXlKVdEE,iv:JBMaeU9+87DST1eujrsNyliyUHUCvNQgGfuIQ/vLX/4=,tag:gL6CHtZhSG1ogQWrJWX2wQ==,type:str]
    #ENC[AES256_GCM,data:kuO5AUeSUCmPT0Ia+EXEKGEegQQ8HhZik9hnh1FFkSdHXDSx0p0a0S2rUQ7dYQY3RAYkVTaofyM+eskuZhAYxPIKpN6X6EGRDaqXLywhLp0=,iv:Vv8a5jj++/cevhDHH7jbO3M1i9UU2au2ZvcxoKG0CfI=,tag:kj5bUSLlLMGRGIZBn/RLbA==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:Sg/WyOcavAkcRGLHow==,iv:3LKPZ6lU2jo6W46hFMg+HqQgO+v6kG28Un+dhleXNRk=,tag:ppUtBobeeya+6oZcvh22gw==,type:str]
    #ENC[AES256_GCM,data:MeW1DDFq+xVfeU4Ewui97iBQEcqy0i8crT7pIp0nSfRhfY3sC2PvGc+t1bdQ77vHn2ZNbRRV1fM=,iv:qDfRw9hWjEhseqT9OHrERMQUqgsUXfrEi1BMLnyzWiU=,tag:hMQQY3INYJog08Ca6MFstQ==,type:comment]
    #ENC[AES256_GCM,data:qgFX3/m/G0pznvntHmUI8eihnNzQzi9Ybw==,iv:pHBEwPFdsxu3Ehh6ZHrRY7uXUN38dOspjfhG9wQpN1A=,tag:gtF9yFe25w/cVFw0o/Mo3Q==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:2uWLV9zaD2tPHWXUCj8jsX0EIj6iIpBDJm0Kmamez+5uWC7GQpUu/tsAPA==,iv:W3AQM7kp8dDrnqdT9K82Qvpg2OfKNCh2HX+EouuTM0E=,tag:LrKVIHPK/ditB/lb/bmsaA==,type:str]
    #ENC[AES256_GCM,data:ofEGXakklaXX2soCoA==,iv:sW4TY/xjadoPcEaOFsyfBlv2ry6VaGQY53QlQxETbu8=,tag:OEkBlwb3jT1hjI8lSOZwCQ==,type:comment]
    PODNET: ENC[AES256_GCM,data:Sv0OWqwXAaqPVdnjsQ==,iv:C0ZSSa9IHglLsvmtX+kVWXLnkFEWS31CWeD5qb2elfU=,tag:FQSxXjZGAUAvOgC58GjS6g==,type:str]
    SVCNET: ENC[AES256_GCM,data:faLLwtJkh9R+0sYf7Q==,iv:p9k6olYDM7yDr+eJADCMOmzI0PqAq1WIesLq+wSlH1k=,tag:/5HDeF8ONySrxrlbwFb1pA==,type:str]
    #ENC[AES256_GCM,data:q40AnuJMEH5hYA==,iv:Me45jYQE8+C0G/AIgUrETnWoK3faz94KeiEuSJh6Iyg=,tag:axxD2e5W/54bZJsVXslzZQ==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:d3YI+7+fZea5Nw2otw==,iv:RuccTXbOqgZ6IBE8jPHz6o61VDW/WsfwwiUgpRCHTlk=,tag:Rft+MmF6qLHQbBe3Kho5Hw==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:yKJyC6RGKMeEHfuZpQ==,iv:RjMf8HHvBQVnH7qAm6XejToB7bCVYwKkdgw1f0ZlhIM=,tag:ddHW4UXe4QEg6NEdTlBesg==,type:str]
    OPENSPEEDTEST_IP: ENC[AES256_GCM,data:HPo9MkD3/W5yrMbb3w==,iv:ZYYC1x5NXvpyVhKCxyZHhgB1a3NfcO9wRJtEnqTQxss=,tag:313hgDMPWY4tqwrSFtKZKw==,type:str]
    MAIL_IP: ENC[AES256_GCM,data:6DwKUWdks27ELrfJOOc=,iv:mhDfwdDK6TEUetYsc1VaxPe4vMeukceqI3a4KwTWryk=,tag:/KpN6knu67W5PZpntLssmw==,type:str]
    TRUENAS_IP: ENC[AES256_GCM,data:uQke1ebFFdcYoJ3BxsE=,iv:tnFZ+8jL7oMHNPo5S0LLmiQPqIyASzJkng+RxYDyd58=,tag:zguDNfNDUOg57D4N1y53fg==,type:str]
    PLEX_IP: ENC[AES256_GCM,data:40UnAX6ExtWzFfKtnBk=,iv:6AYZJ1/g4NOlcWD86AnXhfUZDHJ4fdPpGgWd4DTK2k0=,tag:CkSa113wt+tztbsYzGzUwA==,type:str]
    HA_IP: ENC[AES256_GCM,data:EjRJ8o98qnVEE6TwZzY=,iv:XLCTWZVB6UkbnTcvpME7FrRfMTCKzejmxyslF2vK5dQ=,tag:/6ZdF3Ef+rZt1iT5faVD6A==,type:str]
    MC_IP: ENC[AES256_GCM,data:bGZ2daekjkaYLyz/Rvo=,iv:29IXmcbXywAEjXgOCuALeiGhFEpr3ObPxNH8l9WGqjU=,tag:2CgnBO11LQU3QKGO8xEguA==,type:str]
    WIREGUARD_IP: ENC[AES256_GCM,data:Zlfw2IjdWvUkcftWSqg=,iv:BgHL0JH53KLbpigZdjphnTkvwc9GsPNNPN3lpAe0IvU=,tag:DeF8ziBXRSZ4Q+KfEW8MzQ==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:UHLzRGU8iJhOtCmN0ohEKERKg5GfC4nQCvCMS6WyYtte12bSlz83iw==,iv:z5yC+JIAUGBUxPVjXy2Z+I7lF9oFyC6WAXbQyzdLD4M=,tag:IPf9/R5G72PMhUi/HqZhNQ==,type:str]
    EMAIL: ENC[AES256_GCM,data:+o19rjIuX5ohPrHJUuh6jhP8DeiuJIL57IYYVilptQ==,iv:7ZjHGzXQvfkO/IY9hmuEqoIgXRxdOJsecp1Cqj3kpb0=,tag:Mtd6bOXXq3J+oyJ2ou2Muw==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:U6swovZ/lJ4DyeCKsg==,iv:4LWYBgPgLjRbYGmz1lzN17fnqON856iVwt9t9J2cv88=,tag:9QE2mv+kFYRuZn3bb4CiUA==,type:str]
    MAIL_BASE_DOMAIN_RL: ENC[AES256_GCM,data:9jpLFQvd9cBRRABzKlle+jJln+DuWuU=,iv:vLfwQ2PZBMGeOc0/GBx5TANdI5eSgBbeE9GH1pP+x7I=,tag:tndPX8PSTbc2mEBi8irKFQ==,type:str]
    MAIL_BASE_DOMAIN_GCL: ENC[AES256_GCM,data:dzb+rmB6O8f0fIR4C/WczEo9LkGIB6H3LzQ=,iv:l4aIU06QNFNVHetmqzpAmFmUiJav0fe4nNK3iTi0s/E=,tag:Aihs4zBoJ/pZqkRa0hO+RQ==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:KNKdWQ==,iv:CEkO9G2FrKumpqdZAKDy5raksBrHqDZBxZYvD3jiyN8=,tag:FpCH+VbTpomTgZOg2obfDQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c8f2w7vn06fj2chqaq274g66mg9z9sf9s4l33wmf7m99g5w2nafqlunj9f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFL1NQU3I3MFZ4MnhVYXRq
            RDRqb2dYYndIeGJnbTIyN1RYYWdOUDBBL0I0CkIzeTRjajN2VkRKVGlTTDNjR0Ni
            N1dMYVJBdkM3M2NnTW1pTjhQcUtyNjAKLS0tIGlENWxVK0gvUTNZeVVYZDFYOGdD
            aXF4dXpFdFlybUZDQnZDRSticXlBcFkKgg23a2gEK8NVe393kYLWOnQNK3d5F8oQ
            GzGuliU44T5jTV3H9zbLgBCWmha1/ObqtlpZ4wRl0Z9+JZ1oBVzqWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-17T16:52:55Z"
    mac: ENC[AES256_GCM,data:RRYMGSh2HS6Gj6AWNafLUf7dnrJhZO/+WJBsK1CKjpayQF2qBcXFsJ8iyhfwS9TSV9yFSIImhjO7fxLjvV+2JEHS3k/g5GyITocFHe2XNfjy9UJMM5chIUBJsyMl3aCSegP67jzULiup4HRSh4pXL4jnFJdVPfg8paO8iIC0vP8=,iv:mfbvVyCBt5z1CJNz9D65AabWudHI34kfamCSDJqBkqk=,tag:uCc3OfcO0jK0Hr3JNQyC9Q==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
