apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:aw8oQ6atyGAdo2TuL/jdX9NHYR1dB98RXhJ/yJsaU8yoidRxT9FSxZPeZ3FmN0MnkfTB1HKmsOV5a8aOBSgXwNI=,iv:m+cXW1GKMn32/kKr5L2yMIHL2AqgAMaec5u2jZy2/nI=,tag:693WlbHFcbYKFPo4ZwWeNQ==,type:comment]
    #ENC[AES256_GCM,data:plslOxVZuidg1/0cpSH+MRKRUwXTbT80g7y/apzBemLzGZ+fdqSWoMu6uTo=,iv:OtbFgzSF9ltxlWwU3jtdNgImI1yXDcH4TCDy9ocMVhg=,tag:4Ep8NxQuwT1qRuyHJyDUHg==,type:comment]
    VIP: ENC[AES256_GCM,data:uVw3115rmSKOISDO1w==,iv:bWiNNijhrDW5V+q/Ij4Tqc6pBGeokOpUSHsRtV9BRlo=,tag:PpgRegJg6cVK+rPKpR2O5g==,type:str]
    #ENC[AES256_GCM,data:OuTNu7LpAKs8DULQi3081aS7fk7KghDCtM8=,iv:48tG9CVthCti64bx0aN/A5+5kw5oMqFP3PemPUYqHKo=,tag:Wjgk3cwbHJTmNozT+eCKbQ==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:hLUkhz62AHOpfNkdBL4=,iv:fDaZHq5xOcqIDD1+M3myx66JlxuR9vl2dBRybez/gM8=,tag:mlHtrHdKuTuajfCqV1s+Bw==,type:str]
    #ENC[AES256_GCM,data:Chr/hUUHQa6dxU2sE/7O7wWnkQ3CQmZ0Rwdl4dYBwxjmuQ==,iv:GvXzhioyernDklXEN3vyzQ3rJSsB1gY9RnB22Q2rI34=,tag:dzWmUx1MGwAZamoq2lHilA==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:TAcg7YskpoLL79tl,iv:ehAcROQ8tmmPnv1KdFX7CFXd2yv4Z4YnLlyCnofP5ak=,tag:/U4mmT8vdt+HwGPWv2L/nA==,type:str]
    #ENC[AES256_GCM,data:7vWDUQvM+GtIqX1r/kxS+Ifu+zKvDNRnSbHNuRurjtCqOF5QyqEr1ZG+Ti0toPE=,iv:2sp73Ueuuxlx6QSNaCLYtYYVu+yYrt8uqJmIywwZ7SE=,tag:T9iwHIfsIIMWe/a2NXxhBg==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:vnSo6wzlP1Qy0RDVIFN6UNv4NgcgQL21FLS2,iv:DmPkMAQw6rTEBvfoVpdgE6XP7fYcd8qpQEcn7I6ZV4k=,tag:Ac3GORYeIevDqWnlnV6wcw==,type:str]
    #ENC[AES256_GCM,data:3ggqBL10Q1jN/oQScqxnS/IY9SnCzPriWEWCTwGA+qASVG0DHT5aF72AAw1KKWznP/bIkYzze3UWTFM8X5KkqgJQj0w/WsghY0UxVtKS7Rs=,iv:iYzoJtsYCVVSdyg2lIS+D0UYazhEe2XEPJ5/pKcvnMg=,tag:bDQBZOQM1hrjpRkH1rBRmQ==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:jzXRl4LkHRXomUkFag==,iv:FRAOYYnKZtrlZcl5qCW80dLqNVWYSOoLJQWic+OOHvg=,tag:mcvOV+EMaYqeCegcIyGEEQ==,type:str]
    #ENC[AES256_GCM,data:97ufCaZPJ8io6AP/jc+7IwRVmpv61ShEaB3meKDknJJTQ6MgkqWKzBjcAHqJE4f/P286ffPPyKQ=,iv:ud+l1apC9AIO3CBpx4DhS6PRqTaQPIlzi+az+UD+TDk=,tag:WqZCXxnOAvpndfoAuYuAvw==,type:comment]
    #ENC[AES256_GCM,data:P2yZjfW2fkUawDJCi0/glmCkaNs5mkZPXw==,iv:XiV0+pSVwjqdb9d48lDgM2pG9ZLSAfQBVJiCcmfn7bk=,tag:zt+r3ZNvregFrgU6iKlxlg==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:EbbJfswSJpCxv+RXAzlnjty0YrFxZbhLahPcOm915fK0Ji6yLzo4KvAx0Q==,iv:s4PKR/yWkvkgnwA0n3YxxoqP4FeAuD1WkJd4AEY0Bu4=,tag:YppPlsaBi7PpMasSybMHEw==,type:str]
    #ENC[AES256_GCM,data:ucjzpmTS68TXm/d1iw==,iv:8tGFo0rdAdMi6oQ047hs4QO2r5l6SqzsSjF0AGpFmIE=,tag:r76URgTByhOAjk2Dv5BDqg==,type:comment]
    PODNET: ENC[AES256_GCM,data:TxyxT45M8xAosPWy0Q==,iv:zlTMQYZ2ArXN2b6c3MHGxP+uY0rzoebXMocK6L573MU=,tag:dTLjh+DVSHVgz0ItvEBUEA==,type:str]
    SVCNET: ENC[AES256_GCM,data:Mytr5Z//NVyQ6ec/wg==,iv:QGc7E6fBKxvfdUXmX5zjBghff3SWkYEGqT+P/80KcC0=,tag:W1BFHK37o2E7OpvWWNW+mA==,type:str]
    #ENC[AES256_GCM,data:yB84kegP16hnYg==,iv:Gr/QHNYrPkUQ1UK/K+Oc3iqj+WLH+ZkZtmn/LZKH2J4=,tag:836CJjiRBhGA0iMzv3cEPw==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:OErn3l+gip2u8sX3Lw==,iv:9dvTBNxdXwQcd9lf2FO9G5qiHER1K7tKOh5s4z+wT4A=,tag:PLJZTNZzT/71Z2yyMGhdkw==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:I8nBiEnu+HwdejkK/Q==,iv:XsGj3piZAs4MyIuOiXK2GxgGwh7zKRUtwMVh8jym8JY=,tag:kV6XMX0+Aw1/3eadks9nrw==,type:str]
    OPENSPEEDTEST_IP: ENC[AES256_GCM,data:EikB92D36TSLykP4+w==,iv:mBHLNAN1ybXP3CavWN6r+fBwFhNaL4kHejvizVpwD2g=,tag:lzsWOY0At01NVVdWAqkyZg==,type:str]
    MAIL_IP: ENC[AES256_GCM,data:dfeQO0KfsROToK9yDJo=,iv:tZsg4EaTqHyJdbJH3Bo6s0wjZcMFoewHzf1/Rk+ds9Q=,tag:+nLu0qDCLk7GvrzQEo4sMw==,type:str]
    TRUENAS_IP: ENC[AES256_GCM,data:JK+E6T+o7aJHEZPMEFk=,iv:xaIapALMKBG+J21rW8BqZDYHSL6Bttc+J5djshSd5KU=,tag:0WqqVZlmVm/CwlV84fk9jg==,type:str]
    HA_IP: ENC[AES256_GCM,data:Qwl9vnZXn+3810qTGHc=,iv:25DGl5DNsXTTLhiXyHikq7fhtfskXCYM06GzIIbLEJ4=,tag:11ZzDpFhfgiPsa1uIU4pNw==,type:str]
    MC_IP: ENC[AES256_GCM,data:ESsBA64BLJX1FWiWhoI=,iv:Suv6BqVlrG9ltXQA1EJ8s14seqhurL60bShv0F10DdA=,tag:nr1jOMvk6buWUDsZHxYnjQ==,type:str]
    WIREGUARD_IP: ENC[AES256_GCM,data:ybud/YQRI3a499jB91E=,iv:23rcVZYzjl9chQrwVhM4yKRn4RDw9P90Nu3PXTBeg5c=,tag:XthARB3qInaHUCTnClPUKg==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:Mbq2upeop2G3z+U6CBjsynkv7T188KXbzsIZeRY8fV9N0WnfCHN7Aw==,iv:u5KeAzE0bLoq9hz/1bz+y0MUUOUNWeU0deo/0iFtWQY=,tag:+1E/VRkBbl4HBQnnpLz1vQ==,type:str]
    EMAIL: ENC[AES256_GCM,data:nDbJS9cRi9Uv71BO9w9xK02xA4qJACiIZtl802NtKQ==,iv:p2HURs39h9MCeB5kXnUaGcC3p1pqi0jsfBelHNe+z5g=,tag:66odJBvDAfpJXCLZuUMBsw==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:duCcXRUODhTXCrbMTw==,iv:OW8J/pkyxK39xODkcgRCJTnkv02dmvlJd1M4a+5WXqk=,tag:2/JVdTYDOQy87dMYVu56Cg==,type:str]
    MAIL_BASE_DOMAIN_RL: ENC[AES256_GCM,data:KY4gxS2jwCNkHZ/cdmtl677z9ashv9Q=,iv:wXONfaw9CLBLhY8q/skW36So4JwdZdTAG+azHsmTJjw=,tag:Xg4Zk2JeG9MCNlHCSZ5Ctg==,type:str]
    MAIL_BASE_DOMAIN_GCL: ENC[AES256_GCM,data:NAmHPnZbnm1MLI1ugYvxcLnFV/xajJrStmc=,iv:YZzZAYv4dsp9oOi1i2mYn0Xi+g9BRArOMo0sv9o6+zk=,tag:bjdZlqwGCJQk0/IlHcQVZg==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:I03uHA==,iv:S84HDnIEuadwZ2dZ1jzGTIN8J3h1xN7ZdknHATRaVZ4=,tag:ealrsjI/Y3VtC2aIOHByLg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c8f2w7vn06fj2chqaq274g66mg9z9sf9s4l33wmf7m99g5w2nafqlunj9f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1MEVSb1dNQmttbEh5NXJ2
            ZlBVTCtPZzFRakQwYkMrbmNnUWFMLzRSekVZCm9XM012cWhzdzUzRVE3ZkNIQzUr
            NEFMR3g0bEczQ0s0SmZKZHJGNHV0MUUKLS0tIGxhZDBEV2YzRlBPbG4xV1B4U0s3
            OE1FWm5yZTlBSGpBb01oWHFGS1ZDRmcKj/2FQn5MWqNVqoyuPGIpLlB2Wy9RbsHb
            f4B5lqj6uyEew74egSc7zlxuReTayPlSqCv6rktw0eUdSTOirP7s8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-17T14:56:49Z"
    mac: ENC[AES256_GCM,data:DEW0rPgQHbcyL9h9BUrnUMlyVXV+8FZ3q1BdEKHQh5fdPt+XAWT0wVAudsB6U3tXjsM9aRWXPz4wxVBSgpJ+8q4LkAiWRYdWQl2+z599wpEv2pBg3jj+r6Lc6mqs+HhnYL0h/IJ5lMBDfWbV4WGnm7dRmmSUZg6XSwcelsNyQJM=,iv:F3hmkN7J3NNSDXlJbdBeni+QVl/BdkN7Qm9rUF+bGyY=,tag:CYMGmTsOYS5xv2tWN9m9xw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
