apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:PTkA5rQmzjMOPQCu9IEHoO3WHrS6TZ4dD/oXRZPDBwVMEhxUsHm63luQtUQr7gKmHdx48D5cYixRZFhpTYMdsAU=,iv:UmJ48Hva+HnlT5c2AxeMBMcBZvJj//u0NjlfxqK4BOk=,tag:0Nq+8/qM8t2SgIur3BcpDw==,type:comment]
    #ENC[AES256_GCM,data:JHnap85l2cahhMdTylYcZ90zIJV5vdag3cU529NrqI404w3qnrpqYYB+mIU=,iv:Jk5PchYZyybhoiYeCXmcXdOvHry44TmBuv8uCsRd6tc=,tag:jofQniELYDMNNmOMsFhlgw==,type:comment]
    VIP: ENC[AES256_GCM,data:TqTIMlJf1tozpskhfg==,iv:0zs04c2/4qAExB0frAohQaKCWqxbT4nCeE4yIzLPFFQ=,tag:+0iknOMmreqoybNG0zMtDA==,type:str]
    #ENC[AES256_GCM,data:QwtTcrjtP7mRIfgCd68tEaflmuhkoXnJgGc=,iv:+7MwrFTKeo9327HooddAzwLQtmvTH+SwcNeY1LnoBlM=,tag:95im8V4+DMTBGoTZW4CobQ==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:M7QbirDU/LaskqAbBkI=,iv:UgrMQG+K7/C2dDVxWANOQyHnNqWvFCwcD/wixKSEmdc=,tag:RaHydg7yKHjRlHp2fWJWAA==,type:str]
    #ENC[AES256_GCM,data:cJjl0UuxGfh5JG8bAQYiBCDirtXCGVb4B/CDsB3BMZNpxQ==,iv:SgjyOmkqyTeiGlB2tZI5yzrF2F+dkZb9PWO3HIKitbI=,tag:hDb4laf5r1oygHvdUF4abw==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:1bJOgg5yL+VVsUs/,iv:vpn0SbHzdFPV6xtyLchRQ4J2W403BW8SZRGTEKncSRA=,tag:3SareicvePKUoULbrYkTtg==,type:str]
    #ENC[AES256_GCM,data:BxuEveqzC2ndw7HY3/oiY85d7N/hoBEoEw4JWisHKCAb0v7KI7sRtR7KH/3BPag=,iv:g/pLMPb6oRPQ9OGGLdsQMkdx5ci5sLMtwyavnsTebDc=,tag:1GhFU9A8KBS8VjoLfupTIg==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:bhjkYyst7j4p2UGkLM8FgmGE2RmB2FtApuCl,iv:4MrtZFbuIQ4fWXGaRQT9LaVHwZHy8muuWA5ANe8lwf0=,tag:2qkz+sewhAEuZVWMNZXVPA==,type:str]
    #ENC[AES256_GCM,data:GU66xnpFK5qIVvWv6+UYhlpiGA+4dq/VEqiU9gjrbjImxGC0Yl04PGd9jRSaxiXPwrGmaPrpYKLlS4WpvNx4GKTLqJjs34PsBmnDTgul8VE=,iv:F3NPPgzlD/bLWzbL5aIodH3SeRLLufFRZJxWd1t0cwg=,tag:isZWmU3cBnLTllAVa1NF+Q==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:A3glqAFXoQR8dO+30w==,iv:qR2hVH9lDfkMpQHstxG8gjI/Gsjsckgfl+Zij6yAzU4=,tag:CkW3jVHzeKfztZissOuYHg==,type:str]
    #ENC[AES256_GCM,data:qvN8xJPxWWeSts70wct+NM+lNY+y3pYRq+qFe2bPtxTcFeJGoKFyNiWOnY+UUEmOwxCfrZlMbQw=,iv:Ijr4VwiDm8Zj3stH06csl5dMf/DU4Awdb1HjvIrrpjs=,tag:jfygSWaxVXN0HJyAeU0MqQ==,type:comment]
    #ENC[AES256_GCM,data:13oCjIOKRYqEy/NYKePjMid/f+gj09Nz2A==,iv:BvhYzksBeGUX21nCyR8gEwHe1DH8DwHipafQ1+z95a4=,tag:IoMH56v+LZHL04ynVUYsfQ==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:jQWoMVMbQw/MVVLkjckCU9doP/Mpw8Wa2jR0a4WQC5mAIPxU/2FZEJ6gaA==,iv:88HRGN1RJGz3KCpGYHKKZJ8QD5CZ4nqzMU2sE1JD2tE=,tag:pKG8Zdv1wSVGjfq4xc0Enw==,type:str]
    #ENC[AES256_GCM,data:PjDyg9xGJcns/UVASA==,iv:SS4PFnARG8OdBO/PX3J7dZ/btX4LthUCsMydIxhqnGc=,tag:5DlyyiPwFpQrAovaQFPvGg==,type:comment]
    PODNET: ENC[AES256_GCM,data:L2nSgQniGTMD0FdjnQ==,iv:SuVU1GHy0r3ErPoHnsX/QuF1uEjVeReSIGXPYhhf9x4=,tag:aCV/PGg6wuy8gLF+u8c8bw==,type:str]
    SVCNET: ENC[AES256_GCM,data:CJOPl96w4EFlgSJBEA==,iv:U3MsPO8o6JApuq+WTzyHQAfycAi+Gd438Yj7GtigIw0=,tag:kn5h/5AIDOZWsCSxyHuj4g==,type:str]
    #ENC[AES256_GCM,data:00MrCfBfRVIv7Q==,iv:frbjzCkTgpN8ZAGhCsw+s6qLiFcDEoxy0ZH0ttSO8Wk=,tag:HFGZ2wOzx/aeFWkYkKsPPg==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:qHkO51NnkKM0Y+lTKw==,iv:p092g8HwPFuMuERPeA1ZJIY2p+y/uEO9uvvlnnNcg6U=,tag:llSHaKkTWMHnmtppFGngCQ==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:m6A6S4Iy23sP66KzxQ==,iv:aV4gtcoSWQNi32YVJ5sG7df6+An88gP4khb2AdZhbDc=,tag:CpDFg+YDSx6Vd4afxSxwZA==,type:str]
    OPENSPEEDTEST_IP: ENC[AES256_GCM,data:N0w5djvpua1oueSC9Q==,iv:c2E+w8hVa73kaSQDY8JAVUH2O052WOwcLDt0FVqsJcw=,tag:MpZoV1OAvk2Xg4ZLAsW1+g==,type:str]
    MAIL_IP: ENC[AES256_GCM,data:LZGCnaUmQmkJJ5mLJgo=,iv:3wh6Jg1SwO0cNOiBZf7vsg4Ph64bOwrj3Zlh5scriGE=,tag:jTDAhkJatdd3dc8J6Rm72w==,type:str]
    TRUENAS_IP: ENC[AES256_GCM,data:6JUKgcDqTzZek0jHjHQ=,iv:/ih15v/SS2uxpr/Yv7z7dVmrrgEK3pZlKAw+LxgCuCA=,tag:u51Rbz9GObcza4UHrZSzmg==,type:str]
    HA_IP: ENC[AES256_GCM,data:pfXa+tc7LdQ2JHSp+5A=,iv:b6UGfpF4hzev0JCquXxZiqEWXEKVO81aLTHeBx3lF/w=,tag:5CP2JMGpzIZ1laTIlm3QDQ==,type:str]
    MC_IP: ENC[AES256_GCM,data:ucMpJlVwX+/gKcOdWMo=,iv:rqmXa1kjLXHtdxicdgYo62q6Iu7TObtzZ3jtBckTyqw=,tag:6Ge9r584fcuCEb9As1i7eQ==,type:str]
    WIREGUARD_IP: ENC[AES256_GCM,data:uS+Dlgqq5N90KOIbADc=,iv:W4rUOKzLtXdTw4gKne2xCfGTqUXMQOo9lQOvMj5pUbY=,tag:FCl6OfSlJLf2R8Fn63Jy2Q==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:ZMYOAgglSbHNPHylXXLHbayP8tN9Anc1kUXPbXxt2FJrgoXqJx8lmQ==,iv:BvKXymkXIbpvWhhKqB/Ez2B19PpPxDTDGZxMiWI5pqs=,tag:5rlDXFBiqdZH4Zxly0lnDg==,type:str]
    EMAIL: ENC[AES256_GCM,data:s3njY7KTzUfyI3d0SqK/q6ftkbQBLWQ5adYZTZyx9g==,iv:qZWBefM2OK6Kh2y/9HaEqwCetxe2nK67umX64V5sJVY=,tag:jdp+r94pSule3pege9jOWg==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:xWlpTFnmwxsVVrmX3g==,iv:NwJLVzhsEtMw855jG2UzXtXPOnCBrI0itwgrKbvLSok=,tag:xOWKHmj+MQQxO63FYWbJZQ==,type:str]
    MAIL_BASE_DOMAIN_RL: ENC[AES256_GCM,data:PgdOrpmQxdlg7hkyy+MRG6WlLfgRRhE=,iv:yEM96ibSMMK/ApEuwcGH+q+Mh7JCULQWT4j/GP0LSnA=,tag:1p/N25jYQRVUeug63fA8Xw==,type:str]
    MAIL_BASE_DOMAIN_GCL: ENC[AES256_GCM,data:QSs4dgsWZQNdnnnbtETbJ+X42Sx+zYmdxYE=,iv:how7uRnYR7WRYcTI8xy9lGimN071EJZwZffw2luKZcg=,tag:ID+R0Ne+sC6b3q7Gh711pw==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:MpAvtA==,iv:WvGq6y9PCxopdKMSFXMI5qJRlHIwZS4UAlXew0eYjNw=,tag:oYSD8aFEm2DziLPn+pXg2Q==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c8f2w7vn06fj2chqaq274g66mg9z9sf9s4l33wmf7m99g5w2nafqlunj9f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxNnlyazJxZ2RodWxhUHox
            QW9OTjIvekQwVFMxTk9CRmRLS2RrZVVKVlhBCk9ZYW9jREQ1cDZkejJYSWpwQ0RD
            WnZuSkxPS3ZEMmxOb056dmFEMHo3akkKLS0tIEp3OTlJd2pDRWhST2lVK3pNN200
            ZnhaYmwyZHEvYnN1NlBYayt5d2htaGMKuiqa2KbRnPM0fC8DlC3EWM38dvhnFN7i
            hyom52vGSW7abZlF5w2C9b6Uw5XJjrZeqj/Hn3nyGnUCO698EBPUWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-17T15:31:35Z"
    mac: ENC[AES256_GCM,data:2hH4GHdIZzk8H0x/Ujb5Va5f/K/Npd44dQyEb/WtiC7RKG9WvO8lXN4GAdnTtW4ywnp1ZkdksgI+VedLbBO2khtrmpz/BZ7FzkAlpxWCw0wC+OZrifTEXwNJY865PHj9V2ZrT33OwYOf+MIAWXUtoxg1IEblxl0hEtyf8yzQGpc=,iv:54h4ZgaN3y67TKXPoc214gkNrilSjTnqveEN7k/W4lU=,tag:ygqm5esl9UY7za24SugAsw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
