apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:wzHAN3r1cXxuWnOMq5AYoGyGRD8dXGst219V5TnE5hjlJfYHfT5N2xI8k5QlC4edGs68f2eCyvkm1TSXj1DXzIc=,iv:uwHClMftnVNHHEDbw3OY738vaKwJkZLLndvBMdSJE78=,tag:upyinhOLFw0bkh1CNfi/1Q==,type:comment]
    #ENC[AES256_GCM,data:/G0TsqfZBsI/FIxg5PevUme5qlcVzCfrXzhItkhgRefLftCJdv+6ksA34ao=,iv:S9ie4FSrI1iOoSG8MbvOSjHha6TrC8dpigMsAckOLwQ=,tag:dSGBjkZgQ6ZYa2HKa2mYmA==,type:comment]
    VIP: ENC[AES256_GCM,data:ydwjj0NQS7BJJHq7uw==,iv:j2k7a9cKb/cErbV5yb7P/h4tNoizmy05mmYmy/H5aio=,tag:jB/vFSC5WnvZPLpJ1Gietg==,type:str]
    #ENC[AES256_GCM,data:Wr2k11BPOhrZXIZQIS++MAFEXh6RyBV1voE=,iv:g6IQjfZYGe1vS98LctTQcNFLzws3Fg1s2jQ3kYXEiFU=,tag:/YZ2X4M2xwVvGCcH5inxgQ==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:VDP4iSeK8B18dwRr0zk=,iv:sNRDpn4I8zx05xIaZJvzmQGqFCYLexeC6CdRYflqJpM=,tag:DYei3KQE6ZsD/WCBLzygGg==,type:str]
    #ENC[AES256_GCM,data:0j8mJ2TdRYvGE/fm6lUh5VZQ0Qiq54eY6lODegW78csRxQ==,iv:lGc5VuX4IBV/eBX4IcGx6Rwk5Ljma0JRWkxzeN1bFzY=,tag:4NGGd5Z+xZNa8gUrLPVh6w==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:1Cs4ShaclOHNYpYA,iv:INIUM/RB8zlF2Kre67gekgrGISx1eH01M2Q5VV9Z3XE=,tag:LbGwvyjdaCBij2Cakqh1bQ==,type:str]
    #ENC[AES256_GCM,data:VAsS/EsCdaDSv6izM0ITekJJIjaodzuKwNPwXezoN1yzruQmUJZc2Zp+Qw1UQ/o=,iv:MJTMiBlomJWsyOkT7GidJCpTRgp4p/5GqQ3w325ro+M=,tag:AQqp4c2v0GrJufuZ3ro/gw==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:wWRZBcNLOXcDHQufLYBAyVbVXwvtTZmxTTts,iv:21aDCxriFlus3tYUBGka3z703uCq8gVuvsrPl44ql04=,tag:i11d4d+Iiru7HVkIP1zcZA==,type:str]
    #ENC[AES256_GCM,data:BDoU1Bf7hjcgvxXHeEaAKV6w33IrgH+WoqHyXkGanxEUn8RQhAReT2fW4dgr1Eik04JBU/cCRmrhE2Qn2xGIWjcKK4qF/DrTva08bTO0JH4=,iv:jg8R4RuS7/P/xU+TD1REt8YIoUDul/5R3Tie4gK2c7s=,tag:suFh2oe7g8OUnbu5j0Qc3w==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:qyEFQxyQwsVLldL2oQ==,iv:c8PbT1/CeSgeiXLVQDP+bssIRvP7FFRylQX4qisxnMY=,tag:7PfKv/pSj/7HPdp+f81dOA==,type:str]
    #ENC[AES256_GCM,data:orK55/OrXEfRnioU5BMifMIaSR4wtPw0mLH27Kbl2iN3RqyXUjp/Q2vfriQpa76D5Qc05XzE+1w=,iv:UQeoi0Tzk7ovtvx9mj4z//B3m0CyoIse2WhCTdk1MpM=,tag:CNEvLMb2gplD1bRutkuvZA==,type:comment]
    #ENC[AES256_GCM,data:4PS5x8To1Fc5uf+kCQ/b4fb/Mh2EK6gESA==,iv:uRt1exzktfhhc6n1iMYFlXE5bkHlA3ud6kpRgHx6/P0=,tag:aq/lGkNxqFQAOX0QUQvDDA==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:SXjP+y6QpdvY4GxBRoaduQPZKTbAxUvlpPqiLox9X+L6OsGmjgHIOFS6hg==,iv:MMRln79ArxIh46svRjlpNEFC1Q1bht53p+R1HyebxUw=,tag:rqsoIdn3fd0Iaj+xFNvJIQ==,type:str]
    #ENC[AES256_GCM,data:C6Glf1hlF13gn6+RMw==,iv:8eiQHGjkTjO171By+zEb8S1Up/HDG8bmaESFu2LMf7s=,tag:6xoKQeYqJ3vW4vZeuTGrfg==,type:comment]
    PODNET: ENC[AES256_GCM,data:VIuXpknekUBeFDqUbw==,iv:pQJsqHCX2umbDPKP9i1D1I0Jz5U/OdGz6C1u7Ink1WU=,tag:C67XkFTiPuNF5YkFKOPl5A==,type:str]
    SVCNET: ENC[AES256_GCM,data:3EQO2BT1OJaalSMA3g==,iv:lufPcy/99BNCW4XuC+81QCFEgVCIpWlf9w/vu3BURTQ=,tag:3GZI4vCRWQbk0EeIGg/o2Q==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:D1aGug==,iv:l1MBVIoUJRt38AHkJeXn59SPSNx+9MdUEHD1nX0y3GQ=,tag:pmNeazeaRJ/ls9A4dk3XBw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c8f2w7vn06fj2chqaq274g66mg9z9sf9s4l33wmf7m99g5w2nafqlunj9f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3NjdmNlloNVFDQUxwU0Ur
            amp6YVY4YldRbEhKa0F2cXJRM3o0ODRIL1FRCkJoMno5YnFRbmFoTUlzNXE4Qnlo
            RjZ1VkIyRzAyUEdHR2tLM0ErdUdkdlUKLS0tIE9qdTF3ZlM4TllVTXUwZExaL0dX
            ZkwxQXh0U3FnQUdiclpFSlZHRHlvWWsKNhcSxLdvuNeJPpvU6yggV9Io0l4SVo3w
            tBPyHq99MqgpZauGMP94k5AfaLnyKu/3rscf9HVId4w010T1Zxroig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-16T23:38:34Z"
    mac: ENC[AES256_GCM,data:a7d9woQ0MrOwpdB8dUt6g2uGBmIB/C1ynifOdgJsDQjbRWL3xAHlT5K5AHMS86fxmTvA4/9+pnkWc0tMyhbhk2OFrWccZ6HfgB6TxIzz0xNlv5LKb545vXEiWDWgTnD0/N/yBZbu3gW3fIWtpMJlQ09pRwXF71Z61XSdXsxb4SU=,iv:2P+S5c8f3wtiwtHNHIlPqXI78OQmronJah3Mi4hk7dQ=,tag:ujDXRAnX2St3dztElRESYg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
