apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:8pHFpG0fgdqTFnZl+qwdcEdDjKnPyvGo/lUEmclv5sdF31r9JocoeteZDMOAz4N6f/j4iVWtQ+cRQYqEbg+Tkt1/aM0pLjK+P5V+l893ABhONsMkvipjuow9zn6/DwOQ24sQwr0XuqNdTmIsAmHad7hWHs9ySezazNoFvxW858eS1Lwrcjw+fvscg7DPT9REJ5fjRJXjKnM8g3200hCGROCKNf+lwtO6B3Qk4Bkg3XwfELoI8PaThlC9UJuUsnCsXzpjguQCCNds3AJuAukceEeEvand2CKm94NqVRCq1ZzwmN3e3jlF35mDz/S+Mrnobw73fKdxB/HnUP/f/1FBLcoS2nJKPiVavARbC5kb+KEfxhl0YInKOZeX7XdOUlJ2,iv:kU8g6YzSuR46hxS8ouHIhaZ5CBmnCxx9/aFeqHyQgV4=,tag:zA6P0vbV8k7QQwOP6oZFOQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:mr0QM+lOzUIZI7gm9fJRjK8bUkTzpi1veWtzTeJERSHFY9CMIHw32cTVKtthWwkISLQV3iuWMhiik7NADTiIe14SVR/Nqxevhwf8HeZZofW8ruwmXkLFFIqYCLQjs7OUiRIQ2T+3hBjDp/EAaBbHciXzjOUuQgR1KN2fu7ZYTAt7RBcgchs1t/EiuuKtP2bRmvXMpi/TGXQPZsrADFBtWrmK5DESlbZV8APeI6MLXyHjwrtH1rSZ6MZ/lxED5uZo/DTUYV9VkdavuXfkUA==,iv:7KrmRlhuqHpCQqICP8hx6tXaUfs1boxOlV/R1igcyaY=,tag:SvSmiSjcuKlhK2HW0J8AMg==,type:str]
    known_hosts: ENC[AES256_GCM,data:tpBCAHVFuLuGy5sXaDs6xZVRN0H971YJWRxv1lsbrl5119UyjXgo35HAtcDgFh150daQwJ5r+v1GtfX9iFJlrXHvtCCJs6vhfcaP3zZQ+ssgFGZyXOfmuofz88dAghrfVBWXycPyxXjEBTmjWEZFd48C+PozKtjEW7dJ3MndNceK/KUgVGH3keXx4XEr0pTFTVej9BlJY10mL+jvJrMm0CeoAyb8n1sYkTFJ,iv:RsNOKQP5ZTBx7NsQRKWaQX4w0vQCeJZzqFW3zyUQaqA=,tag:PKAeeuHRNqQ1HczT1Y/GLg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c8f2w7vn06fj2chqaq274g66mg9z9sf9s4l33wmf7m99g5w2nafqlunj9f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEWjhwZjVjcXFSMk1NVi9X
            SVpOOW12Y1phUmtwcTdwZEJWYno2bFQ3OXdBCjBjM3h3OTlicHNtOU45NklCRmdw
            NjlUVFF4SE9jUVFpa2UzVUFBbm9nRFEKLS0tIElKTWRPV1R0RzF1TlQzQ1lNNUMr
            b1IwaVRSeHkxTDR0bW1xUFo5cTZYbjQK5B1hLQyLvRIf3mKhsa0k95X54GjyrgXM
            LCYuD1qFm+/wbb+VULPCsZEg6QouItq7xtCTc5bpot5+IpcLe3ZtAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-17T16:52:56Z"
    mac: ENC[AES256_GCM,data:ECXBH1eKlhBpQy0UxoDrAN3irnqlvai31Azpn48g5Vta4oxzKbuEjZhQVn5pSVU6nOE5lvZL6ljYQZHlJB95F3bksFeO+Dn150Oq8l1Pm3oZrEc2xG2vv/WONTnmN5mSpiyp+ePnldMijMWX9nxDJtnz2vfI5l6PDzkXXRqUBFM=,iv:7lIae7M1NW97Q+dhbulOl4dzfY/gx2f3W9vU7cx3p7U=,tag:TEXEG4BUVYHyGMb4u0xkZA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
