apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:xsyvTyi/8vgEWmXcqxIdajfypYX5DPOkt04Q7zeBDJvecTnK49r57hC97AgsBuV3pUR3SX12MSej/r8gobn0xIKxBmz6HF9w7mFZCy7o86c18AZqkbo5OSnoJfkEZ/aJm+fjflcT5cH4F4F87PaV0LMTkMZ2GjGjQ5lDXiZ+x714MBR0a00kqDYvu7lONXDEb9KwMA+FxLwHUVAOMCgrdkIEpo5DVT8iORqRGcsWGvd8FbpeGvuKUlsQQJySQY95OwtRIpY6nxhtIuSUChKGNYEIk/F4FAr1V2qTT75uR6EqrChagqGlfJbig4oCR/k13id5QV9giKqS1jKy7vB4OJNthMpCqvGbIKd6hLli9d/axEqUaKFkgop5+V/xxB8g,iv:uZyicxdqoYG7I1vQWdmcJsbhUPa2wYM/ozi/kFAMP08=,tag:mhUMSnXwb3+G9u8E2+CZsw==,type:str]
    identity.pub: ENC[AES256_GCM,data:ZRfJ2bttwYl1yi7IK4OmHiYcNujOHYX2rGCQ8bdV7nQZ/u9E5uwwOXtB2w79gFSLx6BKDwd3HeFpVuTYHkFGrA4N/JnT/ryT2WzkCL74ZIf71SP63geDhcO9EKxMYMEcmuF0x1lEYBLrQxuRITQJx9/dOAXf2vHIOFnmO7IxnAXeFWgmwgY2nMVboRceN8kUVTRJYVz7s1flLEHUCsOgKGFWXzzjUyzEldIbNvwbF4eALtM0QrXBRca8tOv4NbGGKd8CVswxxg1e9MDgAA==,iv:CBIv/iDSsrnpACxUH6q7xtNQUh6Yofo3Iv8wjiJU+fU=,tag:meu57CeRlYP90QWlN+uGmg==,type:str]
    known_hosts: ENC[AES256_GCM,data:MGXLY6OTkZugX5Ub6DF5+reDWxBDYeY6e6iIKkuEmNIvaj98kisdmuXnxSC+7eI20gzIgdeOVXDIMUwrfQSufChLdC2ZXsjsmlo6H9mdz3le61S2mF+CsF12llYk+C0R3NdKbkfJJyrywvCdh9W61p2CrzBBe0qleUapWYa7nOU4C0L27xJDA8FHYnZOFc3AHm18sToknompAexBgWGsy5pSz6YDOWGZ5XzI,iv:9Qro69+V3F48NCLL1Om9Y8OE8wZY48lTmnqXlJrU/aI=,tag:vdD7IQ6rbdCvMgA9eeBP1w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c8f2w7vn06fj2chqaq274g66mg9z9sf9s4l33wmf7m99g5w2nafqlunj9f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEb0VpdkNKYkNoVlg4U1FX
            d3dNTENmV2dwaWd6ZWNIVTBCcTlqL2VtLzEwCjlRVHlPY2d3S0N3NjVxZnpqaDE1
            c3lxSGZ5bkVtekI2bEE5RmdPajZ5NlUKLS0tIElCZ0xya1NTclhrbmpKV1dvQ2Vw
            R1pKMUoyQTlOdWtINmRTNnRwcUEyVFUK44YU37SeDDC+aJL+b/0qaz9QbrjHcAoI
            +sc1cM7EBLOzQnD/yyHWBoau6zlVRrAV7d891ZZGRDJl+1jz+ilfOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-17T15:50:14Z"
    mac: ENC[AES256_GCM,data:/di4aX/Nq3eQHEYKh4tRbRXcoXjRP+EoojKloJoLGvpvJIW5bhppz1ZD4X00jvudM1Gasxq/4WDfwHsi0McooqjvfsZMkHEzaJ9i2qDU3F6co5ILWH79lbcVsNqXCWRHm1VWUmfCHv/QhatKPYMkVM7XZXmVs87f6fphZIi+QgA=,iv:ZRb14XzIPCvqDF3pz2qCJQfQHXl35KcimbPSSOwaHx4=,tag:KbHNLurBgOma9S9R/bLs/Q==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
