apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ni8JoBETkX+a5743KHNBo2cnsdKAZ76tmYVFvqU/oO1IlIqWbOXRtfBuZChpI9f8tLUoGuvK4Kce53NZahwRW4jItLPTT8ZEBrCOPZ867dyDBHgkeKz/shM7bOCJ/g6PaAqifqMRu5HJqVbQjliMWdQzWJFOqM0cY2V9OhJfXH+brgIsERH5gzds2GGSsPOJp7R1UdaJi8GThepp8e5c3/fnLgsYVNIUj+B4XRmVxMzHLzrUrFYR/MwI1M7IBzVD872V/woqkeH0NudRb97My4yHYSGyh8HPcIdLPu+m2PnVL5qs1+WpV4NEtOcta0IIAwbwAD5Msx3x6xde0Fbfss05GzdiJ3Eh60yqXturzL6ZmgB2rQKB+xNx9tOZM5mW,iv:LNgM5yryYXUJeUtBXOm6zt4BNktoRcy9/ug77DRqTjs=,tag:kQ4FOY3CcimL9VtiYaCzCQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:5g2/CJ0Ybm+CevmVTRNqmWTo1D0L+bY/pHSpu9UJ6xXhc2lyg+My8L4M0DJK5ugyTXa43ppQOPQspQnfL4N6ffYeuvdnmqUIzGrPPuZZobFeaTqDJwO8EiXivmL/db11E8vEGyYhz7efE6+mfudPZfuSz/P0uQ819MBqS3btRfQywrkrc2v3IJq0s4jtMDZa8Xh5vJY1oO4M9oA56MhYg9tUae895A/GdnndR4thFVEBtiZowBRaUkpgOpR90gSchHPr4TCObYsZl3tOGg==,iv:R/HQHXiXm78B9MrH2DrwUPN2cUd4IdjrDOd5JVdcsrg=,tag:D0t0athLNSer9njgPTVIlw==,type:str]
    known_hosts: ENC[AES256_GCM,data:o+oPdhIe9gVPUcpjknJKw729FTXF8qRFXfwYtNNujEB3od8fjN7fD1glTGDvDMgG70EOE+UsHT3y9Evzb6nxpA9B2E8qjkFqJDrfKy91YsC13ce6zcUEoxyuhUH58QiWumDZRvQw/7SGKOAS1j0FJPy1thLiX/mmCj9LkyEcDDGjNPgq5Vk+3BNe63LaOOomy6lHQtbr2Rmedzxaz1X4fRhMs6to/FNKwogq,iv:nLqcGzKGjpgewbLM6/jvPJ4wVIjNOvc2HW01C8WJmYI=,tag:O34a4yCfAOd+cqV/R2561Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c8f2w7vn06fj2chqaq274g66mg9z9sf9s4l33wmf7m99g5w2nafqlunj9f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKdFQ4ZkVuK2Y0RXJHRFAz
            Tm1uY09aN3ExaDNhMXBadmtwZnYyZ3NRUVh3Cm45QjJRUThmamYvQVNyaUxQTDJV
            azl2eGZBSlVxdVJZb3pBZGNBOVVGWDAKLS0tIHRoNU5RR2hmWGEyM3AySm5aVDZX
            ci93M1Rsd0tmbmdMOFZER2FYSTh0VVEKcYhYNnJrF8bfniSRW7aKHJlSKUKHlxTq
            uugYkHkSy1c7czGNnfvbBjdJ/Q023tauSdDjU4/6Pg0eZJwZ4Y4yxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-17T15:59:04Z"
    mac: ENC[AES256_GCM,data:ZDbq4ikHFg8/UEwIMkI9TtfzlCwnC+3y8gQf9qkHkqdraJmTynLi7eu0cCb0O+70RhotP5WJNQu+45copqF7R9dtUE+XezrXnckHIAdsMlNLhDI85tsAb2/IBx7tlSjAKAWXDTXvN2Am6PPfF4q7P4ZwycDhE3kd4k7YlSXAQ84=,iv:WoSk6P/4KVPw5eE1nPAVqWQ9mOlKXkiZM6aCapENhEo=,tag:ISO9b1uB313M2j9ufUnWTg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
