apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:pJfbsT8wVdU7xMeTFqZVi+OHauplzfJFutd3tchzuCch9hu2f7S+7UexZlOPot3PLN+QNLfmgY7LOlQbPFD8PYdcHlk5ShVwcHlaCIc95oSwUZYrL7aAqdaVR5V28Hve4DXRbTVIrBCKGenS43GkrCgNvJm/Mz8lqM1WhrR2MC3gzPruUosdBaHynmcvlIfG/Zqn93e/paT/mn0/6XTO4+/4mGN0bl27f1VsI5l2FhiW8gel/joTtgGMUyv2sIbU6Tm8zyqYWc90aCZyW5JS5ySS0oqtnbYBfUbOvuciXFK+bdGJyb5dMNrzbydR06caxNONMUmqRgxelIWgxel/HVEiTPT/76MAicsuAPpGC8H7oRHekmH1NU8UUUgdII/k,iv:ZLDF4rC6Yg8Dfm/PMLtl09Y7u2wTa6yHdPa5Vxk67AY=,tag:UNMGWrgdviHE+SI9FbEYSw==,type:str]
    identity.pub: ENC[AES256_GCM,data:S/2OZzFn1/RcUO3ge/bmTyju6GllRrBoaeOTAfWbK+i3nxkGcHxHgLzJeFJcdH4S/uGEKwrLsMwvnJujSmtydqjWpDKSu7wo3BRDFss2fMxNyRz21QNKLd5z/YlxkznKrN93hIELBHldBNoeQzlUykzOyD9YM/UESUAEe4VsvAHDyWHt9HE9CP1MCiixbjb6a1sodOQUDXQgZemc/w8zN5k/Ce/nd6dtPKWZJA22qxs9FcDeIbMPaj6DKqhAsiTtz8IeWKKnD9wnVftm1Q==,iv:hbLw0/qFL8cofn3tUwvue+2jU7syWbIlfNoV2fCgzIk=,tag:KTumCrhKsXc5kmm3WsUhtg==,type:str]
    known_hosts: ENC[AES256_GCM,data:4XkL192hRIzfKm6LHUm7aqz4MDstMbthUx2aEnXOJShAfEbQ5o/t1QhfaBltX5jPZ1bsztX46LMm9poWwHvCYvEUHR4OxBtCq6NRsQv3WlSJFnbWmPT+mUUF2bUhG2W5Oz/atoNiyTriWSPy7Z0Qby+sUuR8Ak7/QT/cAwDu7T6mXqdXND6HgGY+mJFZh1ycvVQEBlEpB3cNSKQskNOe08ykOY8trVqs0Ued,iv:de9Znd7425RcfCDNdOZ8O3Aczv1SkzDEaH/cAqDsjN0=,tag:HemwNOriUUAQIjjzcUSj/g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c8f2w7vn06fj2chqaq274g66mg9z9sf9s4l33wmf7m99g5w2nafqlunj9f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ajBPd3Q0cVJMUlN6eHFX
            UWJ6OE4vTEdabzRNWmFwMGZkSEFFbGN3OUFnCk84eWtLWkk1eHB0c2FLd1A2aFMy
            bkptWFFnMnRjZEZLWkZJTE5ieUdhRGMKLS0tIHVuYnhKZm9RYUY3ellaOE9PNFAz
            ay9CdmpJSDhBTXVvdDFHR29MNEVNRVUKcH9cdwRizvRQDp/2lhA+O+9/cE0rtipj
            5LNDADcDSO2nXvj8SZyLOdL26W8SYwrtAJAiQEj0fUYdNU4sLgcR4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-17T15:56:48Z"
    mac: ENC[AES256_GCM,data:72jwJorZLaS/Yo7SSJ4m7hGcqJjwgVUPQVLNVmkRrP0vqLJnPXHwRy1d7H7LHWyln2MpT35TJ1mmY7je5DxYqGSF17N8FBaIiumlAOx8+g62u4DAyRI7yvwK/frSi+eOfGI/OwqHnuXb9eLtVEw3epW07PPDFyKwORdaEMaxs6A=,iv:v+avCmN1JytS90C8E2nqPYI9+Lyrv6D/YnHMIBGPYZI=,tag:4gjyU36sGm2uz30Q8VEkvA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
