apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 15m
  chart:
    spec:
      chart: traefik
      version: 29.2.3
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:

    service:
      main:
        type: LoadBalancer
        loadBalancerIP:  ${IP_TRAEFIK}
      # tcp:
      #   loadBalancerIP: ${TRAEFIK_IP}
      #   externalTrafficPolicy: Local
      #   ports:
      #     web:
      #       enabled: true
      #       port: 80
      #       protocol: http
      #       redirectTo: websecure
      #     websecure:
      #       enabled: true
      #       port: 443
      #       protocol: https
      #       # -- Configure (Forwarded Headers)[https://doc.traefik.io/traefik/routing/entrypoints/#forwarded-headers] Support
      #       forwardedHeaders:
      #         enabled: false
      #         # -- List of trusted IP and CIDR references
      #         trustedIPs: []
      #         # -- Trust all forwarded headers
      #         insecureMode: false
      #       # -- Configure (Proxy Protocol Headers)[https://doc.traefik.io/traefik/routing/entrypoints/#proxyprotocol] Support
      #       proxyProtocol:
      #         enabled: false
      #         # -- Only IPs in trustedIPs will lead to remote client address replacement
      #         trustedIPs: []
      #         # -- Trust every incoming connection
      #         insecureMode: false