---
# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: qbittorrent
      version: 22.1.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    # credentials:
    #   s3:
    #     type: s3
    #     url: "${S3URL}"
    #     bucket: "${S3PREFIX}-qbittorrent"
    #     accessKey: "${S3ID}"
    #     secretKey: "${S3KEY}"
    #     encrKey: "${S3KEY}"
    service:
      torrent:
        loadBalancerIP: ${TRAEFIK_IP}
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
            middlewares:
              - name: local
                namespace: traefik
              # - name: bouncer
              #   namespace: traefik
          certManager:
            enabled: true
            certificateIssuer: mb-wildcard
        hosts:
          - host: torrent.${BASE_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
    persistence:
      media:
        enabled: true
        type: nfs
        path: /mnt/bigdata/plex # Big Data
        mountPath: /plex
        server: 192.168.68.109